{{- if .Values.repositoryPvc.create }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{include "tuna-fusion-gitops-server.repositoryPvcName" .}}
spec:
  accessModes:
    - {{.Values.repositoryPvc.accessMode}}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{.Values.repositoryPvc.capacity}}

{{- end }}