apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agentbuilds.fusion.tuna.ai
spec:
  scope: Namespaced
  group: fusion.tuna.ai
  names:
    kind: AgentBuild
    plural: agentbuilds
    singular: agentbuild
    shortNames:
      - ab
      - build
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                gitCommitId:
                  type: string
                builderImage:
                  type: string
                buildScript:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Scheduled
                    - Running
                    - Succeeded
                    - Failed
                    - Terminating

      subresources:
        status: { }

