server:
  port: 8080
logging:
  level:
    ai.tuna.fusion: debug

javaoperatorsdk:
  reconcilers:
    agentDeploymentReconciler:
      clusterScoped: false
      namespaces:
        - tuna-system-dev
        - a2a-samples-ns
    agentEnvironmentReconciler:
      clusterScoped: false
      namespaces:
        - tuna-system-dev
        - a2a-samples-ns
    podFunctionBuildReconciler:
      clusterScoped: false
      namespaces:
        - tuna-system-dev
        - a2a-samples-ns
    podFunctionReconciler:
      clusterScoped: false
      namespaces:
        - tuna-system-dev
        - a2a-samples-ns
    podPoolReconciler:
      clusterScoped: false
      namespaces:
        - tuna-system-dev
        - a2a-samples-ns
operator:
  builderImage: "ghcr.io/tuna-headquater/fusion-a2a-env-builder:1756169952"
  runtimeImage: "ghcr.io/tuna-headquater/fusion-a2a-fastapi-runtime:1756169952"
