global:
  image:
    pullPolicy: IfNotPresent
    tag: "1754730088"
  clusterScoped: false
  additionalWatchedNamespaces: [ ]
  executor:
    servicePort: 8080
    serviceName: ""
  gitOpsServer:
    servicePort: 8080
    serviceName: ""
  archivePvc:
    accessMode: ReadWriteOnce
    create: true
    capacity: 100Gi
    name: ""
  imagePullSecrets: []