[project]
name = "tuna-fusion"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "a2a-sdk>=0.2.5",
    "google-adk>=1.2.1",
    "kopf[dev]>=1.38.0",
    "kubernetes>=32.0.1",
    "pytest>=8.4.0",
]
