server:
  port: 8081


spring:
  main:
    cloud-platform: KUBERNETES
logging:
  level:
#    org.eclipse.jgit: debug
    ai.tuna.fusion: debug
    root: info

gitops:
  source-archive-handler:
    type: ZipArchiveOnLocalHttpServer
    zip-archive-on-local-http-server:
      zip-repository-root: /tmp
      # assuming the namespace is `tuna-fusion`
      http-server-url-template: "http://gitops-server.tuna-fusion.svc.cluster.local/source_archives/${fileId}"
