server:
  port: 8081
spring:
#  application:
#    name: tuna-fusion-gitops-server
#  config:
#    import: "kubernetes:"
  cloud:
    kubernetes:
      client:
        namespace: default
      config:
        namespace: default
  main:
    cloud-platform: KUBERNETES
logging:
  level:
    ai.tuna.fusion: debug

gitops:
#  source-archive-handler:
#    type: FolderOnFilesystem
#    folder-on-filesystem:
#      local-source-archive-root-path: /tmp
  source-archive-handler:
    type: ZipArchiveOnLocalHttpServer
    zip-archive-on-local-http-server:
      zip-repository-root: /tmp
      http-server-base-url: "http://host.docker.internal:8081"
  watched-namespaces:
    - tuna-system-dev
    - a2a-samples-ns
