server:
  port: 8082

spring:
  cloud:
    kubernetes:
      client:
        namespace: default
      config:
        namespace: default
  main:
    cloud-platform: KUBERNETES
logging:
  level:
    ai.tuna.fusion: debug
executor:
  informers:
    clusterScoped: false
    namespaces:
      - tuna-system-dev
      - a2a-samples-ns
