{{- if .Values.configmap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "tuna-fusion-executor.configmapName" .}}
data:
  application.yaml: |
    server:
      port: {{.Values.app.serverPort}}
    logging:
      level:
        ai.tuna.fusion: {{.Values.app.loggingLevel}}
    executor:
      informers:
        clusterScoped: {{.Values.global.clusterScoped}}
        namespaces:
        - {{.Release.Namespace}}
        {{- range .Values.global.additionalWatchedNamespaces }}
        - {{ . }}
        {{- end }}
    {{- end }}