@startuml

[*] --> Staging

state Staging {
    [*] --> StagingPending
    StagingPending --> StagingBuilding
    StagingBuilding --> StagingDeployed
    StagingBuilding --> StagingFailed
    StagingFailed --> StagingPending
}


StagingDeployed --> Production

state Production {
    [*] --> ProductionPending
    ProductionPending --> ProductionBuilding
    ProductionBuilding --> ProductionDeployed
    ProductionBuilding --> ProductionFailed
    ProductionFailed --> ProductionPending
}

ProductionDeployed --> [*]




@enduml