apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "tuna-fusion-operator.configmap" .}}
  labels:
    {{- include "tuna-fusion-operator.labels" . | nindent 4 }}
data:
  application.yaml: |
    {{- toYaml .Values.operator | nindent 4}}
