apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "tuna-fusion-operator.configmapName" .}}
  labels:
    {{- include "tuna-fusion-operator.labels" . | nindent 4 }}
data:
  application.yaml: |
    server:
      port: {{.Values.app.serverPort}}
    logging:
      level:
        ai.tuna.fusion: {{.Values.app.loggingLevel}}
    javaoperatorsdk:
      reconcilers:
        podFunctionBuildReconciler:
          clusterScoped: {{.Values.global.clusterScoped }}
          namespaces:
            - {{.Release.Namespace}}
            {{- range .Values.global.additionalWatchedNamespaces }}
            - {{ . }}
            {{- end }}
    operator:
      leaderElection: {{default (gt (int .Values.replicaCount) 1) .Values.app.leaderElection}}
      sharedArchivePvcName: {{include "shared.archivePvcName" .}}
