apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "tuna-fusion-operator.configmap" .}}
  labels:
    {{- include "tuna-fusion-operator.labels" . | nindent 4 }}
data:
  application.yaml: |
    server:
      port: {{.Values.operator.serverPort}}
    logging:
      level:
        ai.tuna.fusion: {{.Values.operator.loggingLevel}}
    javaoperatorsdk:
      reconcilers:
        podFunctionBuildReconciler:
          clusterScoped: {{.Values.operator.clusterScoped }}
          namespaces:
            - {{.Release.Namespace}}
            {{- range .Values.operator.additionalWatchedNamespaces }}
            - {{ . }}
            {{- end }}
