{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tuna-fusion-operator.serviceAccountName" . }}
  labels:
    {{- include "tuna-fusion-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}

---
{{- if .Values.clusterRole.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tuna-fusion-operator.clusterRoleName" . }}
  labels:
    {{- include "tuna-fusion-operator.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
rules:

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [ apiextensions.k8s.io ]
    resources: [ customresourcedefinitions ]
    verbs: [ list, watch ]
  - apiGroups: [ "" ]
    resources: [ namespaces ]
    verbs: [ list, watch ]

  # Framework: admission webhook configuration management.
  - apiGroups: [ admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1 ]
    resources: [ validatingwebhookconfigurations, mutatingwebhookconfigurations ]
    verbs: [ create, patch ]

  # Application: read-only access for watching cluster-wide.
  - apiGroups:
      - fusion.tuna.ai
    resources:
      - podpools
      - podpools/status
      - podfunctions
      - podfunctions/status
      - podfunctionbuilds
      - podfunctionbuilds/status
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{include "tuna-fusion-operator.clusterRoleName" .}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{include "tuna-fusion-operator.clusterRoleName" .}}
subjects:
  - kind: ServiceAccount
    name: {{ include "tuna-fusion-operator.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
{{- end }}
