apiVersion: v1
kind: Service
metadata:
  name: {{ include "tuna-fusion-gitops-server.fullname" . }}
  labels:
    {{- include "tuna-fusion-gitops-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tuna-fusion-gitops-server.selectorLabels" . | nindent 4 }}
