[project]
name = "fission-a2a-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "a2a-sdk>=0.2.9",
    "fastapi>=0.115.14",
    "httpx>=0.28.1",
    "uvicorn>=0.35.0",
]
